### PR TITLE
use `?` instead of `try!`

### PR DESCRIPTION
**Pull request by niklasad1**

### CODE REVIEW

**Comment by niklasad1** [comment]
> (Although I don't think try! is deprecated, is it? Not recommended for sure, but does it print a warning?)

my bad the warnings appears only on the nightly toolchain

**Comment by ordian** [comment]
Does it affect generated code?
FYI: https://github.com/rust-lang/rust/pull/62672#issuecomment-511402922

**Comment by dvdplm** [comment]
@niklasad1 can you rebase please? :)

**Comment by niklasad1** [comment]
> Does it affect generated code?

The binaries are not identical  but I benched the following:

```rust
pub fn try_operator(a: Result<usize, usize>) -> Result<usize, usize> {
    Ok(a?)
}

pub fn try_macro(a: Result<usize, usize>) -> Result<usize, usize> {
    Ok(r#try!(a))
}
```

`try` was ~1 ps faster...... seems to

**Comment by ordian** [comment]
> The binaries are not identical but I benched the following:
> 
> ```rust
> pub fn try_operator(a: Result<usize, usize>) -> Result<usize, usize> {
>     Ok(a?)
> }
> 
> pub fn try_macro(a: Result<usize, usize>) -> Result<usize, usize> {
>     Ok(r#try!(a))
> }
> ```
> 
> `try` was ~1 ps faster...... seems to

The problem was with more complex (nested) expressions and the compiler not being able to optimize the overhead away. I think it's fine in our case.

**Pull request merged**
